# modified from: https://github.com/purescript-contrib/purescript-argonaut-generic/blob/main/.github/workflows/ci.yml
name: CI

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up a PureScript toolchain
        uses: purescript-contrib/setup-purescript@main
        with:
          purescript: "0.13.8"

      - name: Cache PureScript dependencies
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-spago-${{ hashFiles('**/*.dhall') }}
          path: |
            .spago
            output
      - name: Install dependencies
        run: spago install

      - name: Build source
        run: spago build --no-install --purs-args '--censor-lib'

      - name: Run tests
        run: spago test --no-install
